name: Code Quality & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ 'lab2/src/client', 'lab2/src/server' ]

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Чтение кода из репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Установка зависимостей
        run: npm ci

      - name: Проверка типов TypeScript
        run: npm run type-check --if-present

      - name: Запуск линтера
        run: npm run lint --if-present

      - name: Запуск автотестов
        run: npm run test --if-present